CodecaineWebsite/Codecaine_server

src/scripts/seed.js

close #10 
根據新的pensTable的新增欄位增加並新增資料
-  10 位使用者（以 lucy、jay、momo 等人名命名）
-  8 組常見標籤（html, css, javascript…）
-  每人發表 3 份作品（共 30 筆），每筆隨機加上 2 個標籤
-  每篇作品有 5 則留言（共 150 則）
-  每位使用者收藏 5 筆其他使用者的作品（共 50 筆）
-  前 3 位使用者彼此互相追蹤
-  **每筆作品新增的 comments_count / favorites_count / views_count**
用途：
測試搜尋、顯示資料

[chore] 更新 seed，增加資料筆數，pens作品增加收藏數、留言數、觀看數

---

src/routes/pens.js

[fix] updatePen 定義錯誤修正

---

src/controllers/userController.js

如題
我的vscode
新加入使用統一的空格設定
第一次會再追蹤 之後就不會有這問題產生了

[chores]調整回傳訊息

---

index.js
src/routes/following.js

-  `GET /api/following/pens` API
- 取得目前使用者追蹤對象的公開作品推播
- 支援兩種排序：`recent` 、`top` (預設 `recent`)
- 若未追蹤任何作者則回傳空陣列與 total = 0
- recent：依 `created_at` 降冪排序
- top：依加權分數排序（views * 1 + favorites * 3 + comments * 5 + 最近三日加10分）
```json
{
"results": [ ...作品列表... ],
"total": 42,
"totalPages": 11,
"currentPage": 2
}
```
1. 可建立 `useFollowingPens.js`，放在`utils`資料夾
```javascript
// useFollowingPens.js
import { ref } from "vue";
import api from "@/stores/api"; // 你自己的 axios instance 路徑
export function useFollowingPens() {
const pensCache = ref([]);
const currentPage = ref(1);
const totalPages = ref(1);
const isLoading = ref(false);
const pensPerPage = 4;
async function fetchPage(page) {
const res = await api.get("/api/following/pens", {
params: {
page,
limit: pensPerPage,
sort: isTopRef.value ? "top" : …
```

[feat] Following 頁(Following推播頁) API 完成

---

src/controllers/userController.js
src/routes/users.js

[fix]調整路由名字

---

src/middlewares/verifySelf.js
src/routes/pens.js

新增查看垃圾桶方法
is_trash = true -> 顯示找不到作品
移至垃圾桶
新增從垃圾桶復原功能
從垃圾桶移除
close #23

[feat] 後端 API 新增/修改/移至垃圾桶/從垃圾桶移除 功能完成

---

src/routes/follows.js

[feat]修正追蹤使用者路由

---

src/controllers/favoritesController.js
src/routes/favorites.js

close #43
是否需要 Authentication：否
路由：`GET /api/favorites/:username`
範例：`GET /api/favorites/lucy123?view=table&page=2`
參數：
| 參數 |型別| 說明 |
|--|--|--|
| username |string| 使用者username名稱（非 ID, 非 display_name )|
| view |string|  顯示模式，"grid" 或 "table"，預設為 "grid" |
| page |string| 分頁頁數，預設為 1 |
回傳資料範例：
```json
{
"results": [
{
"id": 150,
"title": "ella 的作品 2",
"description": "這是 ella 的第 2 份作品。",
"is_private": false,
"created_at": "2025-06-05T21:22:32.806Z",
"updated_at": "2025-06-05T21:22:32.806Z",
"favorites_count": 3,
"comments_count": 5,
"views_count": 62,
"username": "ella",
"user_display_name": "Ella",
"profile_image": null,
"is_pro": true
},
{
"id": 136,
"title": "jay 的作品 3",
"description": "這是 jay 的第 3 份作品。",
"is_private": false,
"created_at": "2025-06-05T21:22:32.746Z",
"updated_at": …
```

[refactor] 重構收藏功能 API：查詢收藏支援分頁與欄位、加入verifyfirebase驗證使用者、拆分 controller

---

src/routes/pens.js

[feat] pens API tag新增 刪除 完成

---

src/controllers/favoritesController.js
src/controllers/followsController.js
src/controllers/usersCainesController.js

與前端pr
https://github.com/CodecaineWebsite/Codecaine_client/pull/166

[Refactor]調整回傳值提供前端使用

---

index.js

[build] 修正http請求，改為https

---

index.js

[fix] 修復部署網站的stripe串接問題

---

src/controllers/followsController.js

[fix]移除追蹤列表的分頁大小參數，將其設為固定值 30

---

src/drizzle/0012_simple_terrax.sql
src/drizzle/meta/0012_snapshot.json
src/drizzle/meta/_journal.json

[build] notify drizzle migration檔案

---

src/drizzle/0013_jittery_silvermane.sql
src/drizzle/meta/0013_snapshot.json
src/drizzle/meta/_journal.json
src/models/schema.js

[feat] 新增 html_class & head_stuff 欄位

---

src/routes/pens.js

[chore]刪除 pens.js 沒有用到的API (GET)

---

index.js

[build] cors 開放自訂網域

---

src/routes/search.js

[fix]  search API 搜尋類型更新為 doses

---

src/controllers/favoritesController.js
src/controllers/usersCainesController.js

[fix]修復刪除檔案後會錯誤在個人檔案內查到資料的bug

---

src/middlewares/verifyDB.js

修改名稱過濾：
- 保留所有語言
- 把空格換成底線(_)
- 刪除特殊字元
用我們的網頁來顯示測試結果：

[fix] 修改名稱過濾 保留所有語言
